##
FROM golang:1.22-alpine AS builder

WORKDIR /appl

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd .
COPY ./internal .

RUN CGO_ENABLED=0 GOOS=linux go build -o srv-basic ./cmd/api

##
FROM alpine:3.20 AS release

WORKDIR /appl

COPY --from=builder /appl/srv-basic /appl/srv-basic

EXPOSE 8080

ENTRYPOINT ["/appl/srv-basic"]
